apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-r1-{{ .Values.modelSize }}
  labels:
    app: deepseek-r1-{{ .Values.modelSize }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-r1-{{ .Values.modelSize }}
  template:
    metadata:
      labels:
        app: deepseek-r1-{{ .Values.modelSize }}
    spec:
      nodeSelector:
        instanceType: "gpu"
        # "node.kubernetes.io/instance-type": {{ .Values.instanceType }}
        #nvidia.com/gpu.present: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.volumeSize }}
          name: cache-volume
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.7.0
          resources:
            limits:
              memory: {{ .Values.memoryLimit }}
              cpu: {{ .Values.cpuLimit }}
              nvidia.com/gpu: {{ .Values.gpuLimit }}
            requests:
              memory: {{ .Values.memoryRequest }}
              cpu: {{ .Values.cpuRequest }}
              nvidia.com/gpu: {{ .Values.gpuRequest }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 30
          args:
            - --model=deepseek-ai/DeepSeek-R1-Distill-Qwen-{{ .Values.modelSize }}
            - --max-model-len=16000
            - --enforce-eager
          volumeMounts:
            - mountPath: /dev/shm
              name: cache-volume
          ports:
            - containerPort: 8000
              name: http
