apiVersion: v1
kind: Service
metadata:
  name: deepseek-r1-{{ .Values.modelSize }}
  labels:
    app: deepseek-r1-{{ .Values.modelSize }}
spec:
  selector:
    app: deepseek-r1-{{ .Values.modelSize }}
  ports:
    - protocol: TCP
      port: 8000
      name: http
  type: ClusterIP
